# Generated by Django 4.0.6 on 2022-10-05 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_calendrier_reservation_terrain_publication_localite'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationGerant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gerant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.gerant')),
            ],
        ),
    ]
